#!/usr/bin/env python3
"""Regenerate the Core grammar/function map from the authoritative TOC."""

from __future__ import annotations

import pathlib

import track_parsers


ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "reference" / "grammar-coverage-map.md"
GENERATED = "Generated by `english/tools/build_grammar_map.py` — do not edit this file."


def cell(value: str | None) -> str:
    return (value or "").replace("|", "\\|").replace("\n", " ")


def render(lessons: list[dict]) -> str:
    missing_grammar = [lesson["no"] for lesson in lessons if not lesson["grammar"]]
    lines = [
        "# Core Grammar and Function Coverage Map",
        "",
        f"> **{GENERATED}**",
        ">",
        "> The Core TOC is the source of truth. Fix curriculum facts there, then regenerate this map.",
        "",
        "This is an **author-only sequence audit**, not learner-facing material. It preserves the exact",
        "can-do, patterns, grammar support and Japanese-L1 risk currently written in the 122-lesson",
        "Core spine. The sequence guardrail is deliberately conservative: lesson N may assume Core",
        "1–N−1, while any narrower dependency claim requires evidence the TOC does not currently carry.",
        "",
        "## Coverage health",
        "",
        f"- **Lessons parsed:** {len(lessons)}",
        f"- **Lessons with two production patterns:** {sum(len(x['patterns']) == 2 for x in lessons)}",
        f"- **Lessons with a JP-risk note:** {sum(bool(x['jp']) for x in lessons)}",
        f"- **Lessons with learner-facing grammar support:** {sum(bool(x['grammar']) for x in lessons)}",
        f"- **Missing grammar support:** {len(missing_grammar)} — Core {missing_grammar[0]}–{missing_grammar[-1]}",
        "",
        "> **Open gap:** Part 2 (Core 71–122) has patterns, expressions and JP-risk notes but no",
        "> `Grammar:` field. The generator marks those rows rather than reverse-engineering a grammar",
        "> explanation from the patterns. Adding those lines is curriculum authorship and should follow",
        "> native review; it is not safe mechanical work while the catalog is under review.",
        "",
        "## Sequence",
        "",
        "| Lesson | Unit / band | Communicative function | Two production patterns | Learner-facing grammar support | Sequence guardrail | Japanese-L1 risk |",
        "| ---: | --- | --- | --- | --- | --- | --- |",
    ]
    for lesson in lessons:
        patterns = "<br>".join(f"`{cell(pattern)}`" for pattern in lesson["patterns"])
        guardrail = "opening lesson" if lesson["no"] == 1 else f"may assume Core 1–{lesson['no'] - 1}"
        grammar = cell(lesson["grammar"]) if lesson["grammar"] else "⚠ **not specified in TOC**"
        lines.append(
            f"| {lesson['no']} | Unit {lesson['unitNo']} · {cell(lesson['level'])} | "
            f"{cell(lesson['canDo'])} | {patterns} | {grammar} | {guardrail} | {cell(lesson['jp'])} |"
        )
    lines += [
        "",
        "## Author audit rule",
        "",
        "A feature is covered only when the learner uses it to complete the lesson can-do. A mention in",
        "an explanation or optional expression does not count. Contextual and Freetalking material may",
        "reuse a Core pattern or label a deliberately memorised chunk; it must not silently turn a later",
        "Core target into assumed productive grammar.",
        "",
        "Before changing a band, check the source hierarchy in",
        "[`curriculum-source-hierarchy.md`](./curriculum-source-hierarchy.md). This map records the current",
        "curriculum claim; it does not make that claim authoritative merely by tabulating it.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    lessons = track_parsers.parse_core()
    OUT.write_text(render(lessons), encoding="utf-8")
    missing_grammar = [lesson["no"] for lesson in lessons if not lesson["grammar"]]
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(lessons)} rows; {len(missing_grammar)} grammar gaps surfaced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
