#!/usr/bin/env python3
"""Build the lean Core evidence ledger from the authoritative TOC.

The ledger is intentionally a triage instrument. It connects every lesson to
the nearest source category without turning a broad source match into a claim
that the lesson, model lines, or exact CEFR band have been validated.
"""

from __future__ import annotations

from collections import Counter
import pathlib

import track_parsers


ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "reference" / "core-evidence-ledger.md"
GENERATED = "Generated by `english/tools/build_core_evidence_ledger.py` — do not edit this file."


# One deliberately broad source assignment per unit keeps the ledger readable.
# Row-level exceptions below capture the cases where that would conceal a
# consequential mismatch.
UNIT_EVIDENCE = {
    1: ("A1 · Giving personal information; Greetings; `be`; personal pronouns", "Information exchange · pp. 78–79", "local-stage"),
    2: ("A1 · Directions; numbers; `there is/are`; place prepositions", "Information exchange · pp. 78–79", "local-stage"),
    3: ("A1 · Describing habits and routines; present simple; questions", "Conversation · pp. 73–74", "supported"),
    4: ("A1 grammar (`can/could`, `I'd like`); A2 function (Requests)", "Obtaining goods and services · pp. 77–78", "mixed"),
    5: ("A1 present continuous; A2 present continuous for future", "Conversation · pp. 73–74", "mixed"),
    6: ("A2 · Describing past experiences; past simple/continuous; sequential linkers", "Sustained monologue: describing experience · pp. 62–63", "supported"),
    7: ("A2 · Future time; obligation; requests; suggestions; modals", "Goal-oriented co-operation · pp. 76–77", "supported"),
    8: ("A2 · Describing things; comparison; `too/enough`", "Information exchange · pp. 78–79", "supported"),
    9: ("A2 present perfect; B1 present perfect continuous and past contrast", "Conversation · pp. 73–74", "mixed"),
    10: ("B1 · Opinions; cause/effect and contrast; relative clauses; conditionals", "Informal discussion · pp. 74–75", "supported"),
    11: ("A2 Requests; B1 managing interaction, passives and extended questions", "Obtaining goods and services / Information exchange · pp. 77–79", "mixed"),
    12: ("B1 · Speculating; conditionals; wish; deduction; reported speech", "Informal discussion · pp. 74–75", "supported"),
    13: ("B1 · past modals; past perfect; past habits", "Sustained monologue: describing experience · pp. 62–63", "supported"),
    14: ("B2 future continuous/perfect; no direct Core Inventory causative item", "Information exchange · pp. 78–79", "mixed"),
    15: ("B2 · opinions, disagreement, interaction management and workplace discourse", "Formal discussion (meetings) · pp. 75–76", "function-supported"),
    16: ("B2 · adjectives/adverbs and differentiated vocabulary; quantity functions are indirect", "Information exchange · pp. 78–79", "partial"),
    17: ("B2 · expressing and qualifying disagreement; C1 hedging overlap", "Formal discussion (meetings) · pp. 75–76", "function-supported"),
    18: ("B2/C1 · cause/effect, evidence, consequences and conditional framing", "Sustained monologue: putting a case · pp. 64–65", "function-supported"),
    19: ("B2 emphasis functions; C1 negative-adverbial inversion", "Thematic development / propositional precision · pp. 139–142", "mixed"),
    20: ("C1 · formal/informal register and differentiated vocabulary", "Sociolinguistic appropriateness · pp. 136–137", "function-supported"),
    21: ("C1 · abstract ideas, argument, concession, evaluation and counterargument", "Sustained monologue: putting a case · pp. 64–65", "function-supported"),
    22: ("C1 · hedging, vague language, reaction and implied stance", "Sociolinguistic appropriateness / flexibility · pp. 136–139", "function-supported"),
}


ROW_OVERRIDES = {
    18: ("A1 · `Can/can't` (ability)", "Information exchange / Conversation · pp. 73–74, 78–79", "supported", "The primary function and modal form now match the beginner inventory; exact model-line naturalness remains a separate check."),
    20: ("A1 `can/could`; Requests appears at A2", "Obtaining goods and services · pp. 77–78", "bounded-early", "Approved pilot: retain as a bounded request chunk; do not generalise this to A2 request mastery."),
    24: ("A2 · Requests; B1 · Checking understanding / managing interaction", "Asking for clarification · pp. 70–71", "bounded-early", "The repair chunks are intentionally taught before broader B1 interaction management."),
    27: ("A1/A2 · `like/love/hate` + `-ing` for preferences", "Conversation · pp. 73–74", "supported", "The rewritten lesson now owns activity preferences and the verb-plus-`-ing` complement."),
    28: ("A2 · Invitations; `would like` + infinitive", "Conversation · pp. 73–74", "supported", "The lesson preserves availability language and now adds the missing invitation function."),
    52: ("B1 · Present perfect continuous", "Conversation · pp. 73–74", "supported", "The working A2→B1 label should be read conservatively as B1 for productive control of this form."),
    62: ("B1 · questions and interaction management", "Information exchange · pp. 78–79", "supported", "Public Cambridge EGP guidance explicitly identifies indirect questions at B1."),
    76: ("No direct Core Inventory item for the combined causative contrast", "Obtaining goods and services · pp. 77–78", "needs-evidence", "The two causatives now share one contrastive lesson; their exact productive band still needs an EGP row-level result."),
    77: ("B1/B2 · service problems, expectations and follow-up", "Obtaining goods and services · pp. 77–78", "needs-evidence", "The service function is supported; the exact level and naturalness of both follow-up frames still need direct evidence."),
    79: ("B1/B2 · workplace estimates and qualified prediction; no exact form match recorded", "Goal-oriented co-operation / Information exchange · pp. 76–79", "needs-evidence", "The future-perfect mismatch has been removed; the replacement estimate frames still need exact form-and-level evidence."),
    84: ("B2 · formal discussion / hedged requests; no exact form match recorded", "Formal discussion (meetings) · pp. 75–76", "needs-evidence", "Naturalness and exact form level remain separate checks."),
    105: ("B2 · comparison with adjectives/adverbs; no exact correlative form match recorded", "Propositional precision / thematic development · pp. 139–142", "needs-evidence", "The C1 inversion mismatch has been removed; the linked-comparison construction still needs an exact productive-band result."),
    112: ("C1 · register, impact and repair", "Sociolinguistic appropriateness · pp. 136–137", "function-supported", "The risky disagreement formula has been replaced by a productive impact-and-intent repair sequence; exact exponent evidence remains open."),
}


def _egp_result(number: int) -> str:
    if number == 62:
        return "public match · indirect questions at B1"
    return "pending · row-level database check"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def evidence_for(lesson: dict) -> tuple[str, str, str, str]:
    inventory, cefr, status = UNIT_EVIDENCE[lesson["unitNo"]]
    note = "Broad source match only; exact pattern level and spoken naturalness remain unproven."
    return ROW_OVERRIDES.get(lesson["no"], (inventory, cefr, status, note))


def render(lessons: list[dict]) -> str:
    statuses = Counter(evidence_for(lesson)[2] for lesson in lessons)
    lines = [
        "# Core Evidence Ledger",
        "",
        f"> **{GENERATED}**",
        ">",
        "> This is a compact **triage ledger**, not a CEFR certification or naturalness audit. The Core TOC",
        "> remains authoritative for curriculum content; this file makes source support and uncertainty visible.",
        "",
        "## What this ledger proves",
        "",
        "- Every one of the 122 stable Core IDs is connected to a Core Inventory category or an explicit gap.",
        "- Every can-do is connected to the nearest CEFR Companion Volume scale, or a broad scale when no",
        "  one-to-one descriptor exists.",
        "- Consequential mismatches are called out rather than averaged away at unit level.",
        "- English Grammar Profile (EGP) work is visibly pending except where a public Cambridge source gives",
        "  an explicit result. The former Cambridge database host did not resolve and its legacy public route",
        "  returned 404 when checked on 2026-08-13; no result was inferred from a grammar label or from the",
        "  Core Inventory.",
        "",
        "It does **not** prove that a model line is natural, frequent, teachable, or retrievable. Those claims",
        "belong to the corpus/naturalness audit and learner pilots.",
        "",
        "## Source and decision rules",
        "",
        "- **Core Inventory locator:** *A Core Inventory for General English*, essential guide, printed pp. 12–13.",
        "  The inventory is selective guidance for teaching, not a mastery test or prescribed sequence. A later",
        "  British Council validation study found many level assignments inconclusive, so a match is supporting",
        "  evidence rather than a verdict.",
        "- **CEFR locator:** *CEFR Companion Volume* (2020), named scale and printed page shown below.",
        "- **Current band:** copied from the live TOC at generation time.",
        "- **Status:** `supported` is a broad source alignment, not proof of the exact two patterns. `mixed`,",
        "  `partial`, `bounded-early`, `early`, and `needs-evidence` require human disposition before a CEFR",
        "  claim is frozen. `function-supported` means the communicative move is sourced but its exponent is not.",
        "- When sources disagree, use the more conservative productive band unless the earlier item is explicitly",
        "  approved as a bounded lexical chunk.",
        "",
        "Primary sources: [Core Inventory](https://www.eaquals.org/wp-content/uploads/EAQUALS_British_Council_Core_Curriculum_April2011.pdf) · "
        "[CEFR Companion Volume](https://rm.coe.int/common-european-framework-of-reference-for-languages-learning-teaching/16809ea0d4) · "
        "[Core Inventory validation study](https://www.britishcouncil.org/research-insight/validating-core-inventory-general-english) · "
        "[Cambridge EGP methodology](https://www.cambridge.org/elt/blog/2015/11/11/introducing-english-grammar-profile-1-building-profile/) · "
        "[public indirect-question example](https://www.cambridge.org/elt/blog/2021/06/23/using-cefr-criterial-features-for-grammar-instruction/)",
        "",
        "## Health",
        "",
        f"- Rows: **{len(lessons)} / 122**",
        "- Statuses: " + " · ".join(f"**{name}: {count}**" for name, count in sorted(statuses.items())),
        f"- EGP row-level results: **{sum(_egp_result(x['no']).startswith('public match') for x in lessons)} / {len(lessons)}**",
        "- Highest-priority source gaps: **Core 76, 77, 79, 84 and 105**",
        "",
        "## Rows",
        "",
        "| ID | Current band | Can-do | Core Inventory evidence | CEFR evidence | EGP result | Status | Decision note |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for lesson in lessons:
        inventory, cefr, status, note = evidence_for(lesson)
        lines.append(
            f"| {lesson['id']} | {_cell(lesson['level'])} | {_cell(lesson['canDo'])} | "
            f"{_cell(inventory)} | {_cell(cefr)} | {_cell(_egp_result(lesson['no']))} | "
            f"{status} | {_cell(note)} |"
        )
    lines += [
        "",
        "## Next pass",
        "",
        "1. Resolve the five named high-priority rows against the EGP before changing any band.",
        "2. Batch-check the remaining grammar-focused rows in the EGP and replace `pending` with an exact",
        "   form-and-meaning result or `no matching entry`.",
        "3. Feed native-review flags into the separate corpus/naturalness audit; do not rewrite the TOC here.",
        "4. After learner pilots, add performance evidence elsewhere rather than widening this ledger.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    lessons = track_parsers.parse_core()
    if set(UNIT_EVIDENCE) != {lesson["unitNo"] for lesson in lessons}:
        raise ValueError("unit evidence must cover every live Core unit exactly")
    if not set(ROW_OVERRIDES).issubset({lesson["no"] for lesson in lessons}):
        raise ValueError("row override references an unknown Core lesson")
    OUT.write_text(render(lessons), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(lessons)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
